filee = input("Enter File to Encrypt: ")
mess = print("Enter the corresponding for each letter.")
hint = input("ALL LETTERS MUST BE LETTERS! ")
a = input("a: ")
b = input("b: ")
c = input("c: ")
d = input("d: ")
e = input("e: ")
f = input("f: ")
g = input("g: ")
h = input("h: ")
i = input("i: ")
j = input("j: ")
k = input("k: ")
l = input("l: ")
m = input("m: ")
n = input("n: ")
o = input("o: ")
p = input("p: ")
q = input("q: ")
r = input("r: ")
s = input("s: ")
t = input("t: ")
u = input("u: ")
v = input("v: ")
w = input("w: ")
x = input("x: ")
y = input("y: ")
z = input("z: ")
print("Your key is:")
print(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z)
cont = input("Your file will now be encrypted, continue? ")
enc = False
if cont.lower() == "no":
    enc = False
else:
    enc = True
if enc:
    with open(filee,"r") as thefile:
        foo = thefile.read()
        foo = foo.lower()
    foo = foo.replace("a",a.upper())
    foo = foo.replace("b",b.upper())
    foo = foo.replace("c",c.upper())
    foo = foo.replace("d",d.upper())
    foo = foo.replace("e",e.upper())
    foo = foo.replace("f",f.upper())
    foo = foo.replace("g",g.upper())
    foo = foo.replace("h",h.upper())
    foo = foo.replace("i",i.upper())
    foo = foo.replace("j",j.upper())
    foo = foo.replace("k",k.upper())
    foo = foo.replace("l",l.upper())
    foo = foo.replace("m",m.upper())
    foo = foo.replace("n",n.upper())
    foo = foo.replace("o",o.upper())
    foo = foo.replace("p",p.upper())
    foo = foo.replace("q",q.upper())
    foo = foo.replace("r",r.upper())
    foo = foo.replace("s",s.upper())
    foo = foo.replace("t",t.upper())
    foo = foo.replace("u",u.upper())
    foo = foo.replace("v",v.upper())
    foo = foo.replace("w",w.upper())
    foo = foo.replace("x",x.upper())
    foo = foo.replace("y",y.upper())
    foo = foo.replace("z",z.upper())
    foo = foo.replace("1",u.lower())
    foo = foo.replace("2",y.lower())
    foo = foo.replace("3",t.lower())
    foo = foo.replace("4",b.lower())
    foo = foo.replace("5",d.lower())
    foo = foo.replace("6",i.lower())
    foo = foo.replace("7",c.lower())
    foo = foo.replace("8",l.lower())
    foo = foo.replace("9",a.lower())
    foo = foo.replace("0","8")
    foo = foo.replace("!","+")
    foo = foo.replace("?","&")
    foo = foo.replace(".","*")
    foo = foo.replace(":","#")
    foo = foo.replace(";","}")
    foo = foo.replace("-","=")
    foo = foo.replace("@","!")
    with open(filee,"w") as thefile:
        thefile.write(foo)
